/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reserve.login;

import reserve.file.JoinUser;
import reserve.data.UserData;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author regin
 */
public class CreateUser extends javax.swing.JFrame {
    ArrayList<UserData> userInfo = new ArrayList<>();
    ArrayList<UserData> businessInfo = new ArrayList<>();
    /**
     * Creates new form CreateID
     */
    private static int line = 2;
    public int count = -1;
    
    public CreateUser() {
        
        initComponents();
        
        setTitle("회원가입");
        setSize(700, 800);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        J_ID.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        
        });
        
        J_PW.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        
        });
        
        J_PWC.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               
            }
       
        });
        
        J_No.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswordMatch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        J_ID = new javax.swing.JTextField();
        J_PW = new javax.swing.JTextField();
        J_PWC = new javax.swing.JTextField();
        J_Name = new javax.swing.JTextField();
        J_Man = new javax.swing.JRadioButton();
        J_Woman = new javax.swing.JRadioButton();
        J_Year = new javax.swing.JComboBox<>();
        J_Month = new javax.swing.JComboBox<>();
        J_Day = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        J_No = new javax.swing.JTextField();
        Back_Login = new javax.swing.JButton();
        J_User = new javax.swing.JButton();
        J_Test = new javax.swing.JLabel();
        J_PStrong = new javax.swing.JLabel();
        J_NStrong = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        J_NoTest = new javax.swing.JLabel();
        J_Check = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("이름");

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        jLabel4.setText("비밀번호 재확인");

        jLabel6.setText("성별");

        jLabel7.setText("생년월일");

        jLabel8.setText("전화번호");

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        jLabel9.setText("ID");

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 9)); // NOI18N
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 0, 9)); // NOI18N
        jLabel11.setText("Password Check");

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        jLabel12.setText("Name");

        jLabel13.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        jLabel13.setText("Gender");

        jLabel14.setFont(new java.awt.Font("맑은 고딕", 0, 9)); // NOI18N
        jLabel14.setText("Date of birth");

        jLabel15.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel15.setText("년");

        J_ID.setText("* 영문, 숫자 포함 8~23자");
        J_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                J_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                J_IDFocusLost(evt);
            }
        });
        J_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_IDActionPerformed(evt);
            }
        });
        J_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                J_IDKeyReleased(evt);
            }
        });

        J_PW.setText("* 영문, 숫자, 특수문자 포함 8~15자");
        J_PW.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                J_PWCaretUpdate(evt);
            }
        });
        J_PW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                J_PWFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                J_PWFocusLost(evt);
            }
        });
        J_PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_PWActionPerformed(evt);
            }
        });
        J_PW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                J_PWKeyReleased(evt);
            }
        });

        J_PWC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_PWCActionPerformed(evt);
            }
        });

        buttonGroup1.add(J_Man);
        J_Man.setText("남성");
        J_Man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_ManActionPerformed(evt);
            }
        });

        buttonGroup1.add(J_Woman);
        J_Woman.setText("여성");
        J_Woman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_WomanActionPerformed(evt);
            }
        });

        J_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        J_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_YearActionPerformed(evt);
            }
        });

        J_Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        J_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_MonthActionPerformed(evt);
            }
        });

        J_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        J_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_DayActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel16.setText("월");

        jLabel17.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel17.setText("일");

        jLabel18.setFont(new java.awt.Font("맑은 고딕", 0, 9)); // NOI18N
        jLabel18.setText("Mobile No");

        J_No.setText("* -빼고 입력해주세요.");
        J_No.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                J_NoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                J_NoFocusLost(evt);
            }
        });
        J_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_NoActionPerformed(evt);
            }
        });
        J_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                J_NoKeyReleased(evt);
            }
        });

        Back_Login.setText("이전");
        Back_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_LoginActionPerformed(evt);
            }
        });

        J_User.setText("회원가입");
        J_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_UserActionPerformed(evt);
            }
        });

        J_Test.setFont(new java.awt.Font("고도 M", 1, 12)); // NOI18N
        J_Test.setText("    ");
        J_Test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                J_TestKeyTyped(evt);
            }
        });

        J_PStrong.setFont(new java.awt.Font("고도 M", 1, 12)); // NOI18N

        J_NStrong.setFont(new java.awt.Font("고도 M", 1, 12)); // NOI18N

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        J_NoTest.setFont(new java.awt.Font("고도 M", 1, 12)); // NOI18N

        J_Check.setText("중복 확인");
        J_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_CheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(24, 24, 24)
                                .addComponent(J_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(J_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(J_NoTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(J_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(J_Man)
                                        .addGap(39, 39, 39)
                                        .addComponent(J_Woman))
                                    .addComponent(J_No, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addGap(242, 242, 242)
                        .addComponent(J_User, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(J_Test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(J_PStrong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                .addComponent(J_NStrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(J_PW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(J_PWC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(J_Check)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(J_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(J_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J_NStrong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(J_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J_PStrong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_PWC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J_Test, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel12))
                                    .addComponent(J_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(J_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(J_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(J_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(J_Man)
                                        .addComponent(J_Woman))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))
                                .addGap(22, 22, 22)
                                .addComponent(J_No, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J_NoTest, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(J_User, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_IDActionPerformed

    private void J_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_YearActionPerformed

    private void J_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_MonthActionPerformed

    private void J_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_DayActionPerformed

    private void J_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_NoActionPerformed

    private void J_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_UserActionPerformed
        // TODO add your handling code here:
        JoinUser userData = new JoinUser();
        userData.fRead();
        
        try {
            userData.sPlite();
            userInfo = userData.returnUserInfo();
        } 
        catch (IOException ex) {
            //Logger.getLogger(CreateNewId.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        
        String ID = J_ID.getText();
        String PW = J_PW.getText();
        String PWC = J_PWC.getText();
        String Name = J_Name.getText();
        String Number = J_No.getText();
        String Year = J_Year.getSelectedItem().toString();
        String Month = J_Month.getSelectedItem().toString();
        String Day = J_Day.getSelectedItem().toString();
        String Birth = Year+"/"+Month+"/"+Day;
        String Gender ="";
        String Type = "N";
        
        if(J_Man.isSelected()){
            Gender = J_Man.getText();
        }
        else if(J_Woman.isSelected()){
            Gender = J_Woman.getText();
        }
        
        String input = ID+"|"+PW+"|"+Name+"|"+Birth+"|"+Gender+"|"+Number+"|"+Type+"|"+"\r\n";
        
        try {
            if(!"".equals(ID) && !"".equals(PW) && !"".equals(Name) && !"".equals(Number)) {
                if (isPasswordStrong(PW) && isNoStrong(Number) && PW.equals(PWC)){
                    if (count == 0) {
                        userData.fWrite(input);
                        JOptionPane.showMessageDialog(null, "사용자 회원가입이 완료되었습니다.");
                        J_ID.setText("");
                        J_PW.setText("");
                        J_Name.setText("");
                        J_No.setText("");
                        Login back = new Login();
                        back.setVisible(true);
                        dispose();
                    }

                    if (count == 1 || count == -1){
                        JOptionPane.showMessageDialog(null, "ID 중복 여부를 확인해주세요.");
                    } 
                }   
                else {
                    JOptionPane.showMessageDialog(null, "틀린 것이 없는지 확인해주세요.");                        
                }
            }
            
            else if(!"".equals(ID) || !"".equals(PW) || !"".equals(Name) || !"".equals(Number) || !"".equals(PWC)
                    || !"* 아이디를 입력해주세요. (영문, 숫자 포함 8~23자)".equals(ID) 
                    || !"* 비밀번호를 입력해주세요. (영문, 숫자, 특수문자 포함 8~15자)".equals(PW)){
                    JOptionPane.showMessageDialog(null, "빈칸이 없는지 확인해주세요");
            }
  
        } catch (IOException ex) {
           // Logger.getLogger(CreateNewId.class.getName()).log(Level.SEVERE, null, ex);
           ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_J_UserActionPerformed

    private void J_ManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_ManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_ManActionPerformed

    private void J_WomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_WomanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_WomanActionPerformed

    private void J_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_IDFocusGained
        // TODO add your handling code here:
        if (J_ID.getText().equals("* 아이디를 입력해주세요. (영문, 숫자 포함 8~23자)") || J_ID.getText().equals("* 영문, 숫자 포함 8~23자")) {
                J_ID.setText("");
        }
        count = -1;
        J_NStrong.setText("중복 확인 버튼을 눌러주세요.");
        J_NStrong.setForeground(Color.GRAY);
    }//GEN-LAST:event_J_IDFocusGained

    private void J_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_IDFocusLost
        // TODO add your handling code here:
        if (J_ID.getText().isEmpty()) {
                J_ID.setText("* 아이디를 입력해주세요. (영문, 숫자 포함 8~23자)");
        }
    }//GEN-LAST:event_J_IDFocusLost

    private void J_PWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_PWFocusGained
        // TODO add your handling code here:
        if (J_PW.getText().equals("* 비밀번호를 입력해주세요. (영문, 숫자, 특수문자 포함 8~15자)") || J_PW.getText().equals("* 영문, 숫자, 특수문자 포함 8~15자")) {
                J_PW.setText("");
        }
        
    }//GEN-LAST:event_J_PWFocusGained

    private void J_PWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_PWFocusLost
        // TODO add your handling code here:
        if (J_PW.getText().isEmpty()) {
                J_PW.setText("* 비밀번호를 입력해주세요. (영문, 숫자, 특수문자 포함 8~15자)");
        }
    }//GEN-LAST:event_J_PWFocusLost

    private void J_NoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_NoFocusGained
        // TODO add your handling code here:
        if (J_No.getText().equals("* -빼고 입력해주세요.")) {
                J_No.setText("");
        }
    }//GEN-LAST:event_J_NoFocusGained

    private void J_NoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_J_NoFocusLost
        // TODO add your handling code here:
        if (J_No.getText().isEmpty()) {
                J_No.setText("* -빼고 입력해주세요.");
        }
    }//GEN-LAST:event_J_NoFocusLost

    private void Back_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_LoginActionPerformed
        // TODO add your handling code here:
        SelectType click = new SelectType();
        click.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_LoginActionPerformed

    private void J_TestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_J_TestKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_J_TestKeyTyped

    private void J_PWCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_J_PWCaretUpdate
        // TODO add your handling code here;
        
    }//GEN-LAST:event_J_PWCaretUpdate

    private void J_PWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_J_PWKeyReleased
        // TODO add your handling code here:
        String password = J_PW.getText();
        if (password.equals("* 비밀번호를 입력해주세요. (영문, 숫자, 특수문자 포함 8~15자)") || password.isEmpty()){
            J_PStrong.setText(" ");
            J_PStrong.setForeground(new Color(255, 255, 255, 128));
        }
        else{
            if(isPasswordStrong(password)){
                J_PStrong.setText("사용 가능한 비밀번호입니다.");
                J_PStrong.setForeground(Color.BLUE);
        }
            else{
                J_PStrong.setText("사용 불가능한 비밀번호입니다.");
                J_PStrong.setForeground(Color.RED);
            }
        }  
    }//GEN-LAST:event_J_PWKeyReleased

    private void J_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_J_IDKeyReleased
        // TODO add your handling code here:
        String id = J_ID.getText();

        if (id.equals("* 아이디를 입력해주세요. (영문, 숫자 포함 8~23자)") || id.isEmpty()){
            J_NStrong.setText(" ");
            J_NStrong.setForeground(new Color(255, 255, 255, 128));
        }
        else{
            if(isIdStrong(id)){
                J_NStrong.setText("중복 확인 버튼을 눌러주세요.");
                J_NStrong.setForeground(Color.GRAY);
            }
            else{
                J_NStrong.setText("사용 불가능한 아이디입니다.");
                J_NStrong.setForeground(Color.RED);
            }
        }
        
    }//GEN-LAST:event_J_IDKeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void J_NoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_J_NoKeyReleased
        // TODO add your handling code here:
        String no = J_No.getText();
        if (no.equals("* -빼고 입력해주세요.") || no.isEmpty()){
            J_NoTest.setText(" ");
            J_NoTest.setForeground(new Color(255, 255, 255, 128));
        }
        
        else{
            if(isNoStrong(no)){
                J_NoTest.setText(" ");
                J_NoTest.setForeground(new Color(255, 255, 255, 128));
        }
            else{
                J_NoTest.setText("형식이 올바르지 않습니다.");
                J_NoTest.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_J_NoKeyReleased

    private void J_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_CheckActionPerformed
        // TODO add your handling code here:
        
        JoinUser userData = new JoinUser();
        userData.fRead();
        
        try {
            userData.sPlite();
            userInfo = userData.returnUserInfo();
        } catch (IOException ex) {
            //Logger.getLogger(CreateNewId.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        
        String ID = J_ID.getText();
        if(userInfo.isEmpty()&&isIdStrong(ID)){
            J_NStrong.setText("사용 가능한 아이디입니다.");
            J_NStrong.setForeground(Color.BLUE);
            count = 0;
        }
        else{
            for (int j = 0; j <= userInfo.size(); j++) {
                if(isIdStrong(ID)){
                    if (userInfo.get(j).getID().equals(ID)) {
                        J_ID.setText("");
                        J_NStrong.setText("이미 존재하는 아이디입니다.");
                        J_NStrong.setForeground(Color.RED);
                        count = 1;
                        break;
                    }

                    else{
                        J_NStrong.setText("사용 가능한 아이디입니다.");
                        J_NStrong.setForeground(Color.BLUE);
                        count = 0;
                    }
                }
                
                else{
                    J_NStrong.setText("ID 형식을 확인해주세요.");
                    J_NStrong.setForeground(Color.RED);
                    J_ID.setText("* 아이디를 입력해주세요. (영문, 숫자 포함 8~23자)");
                    count = 1;
                    break;
                }
            }
        }
    }//GEN-LAST:event_J_CheckActionPerformed

    private void J_PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_PWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_PWActionPerformed

    private void J_PWCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_PWCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J_PWCActionPerformed
    
    private boolean isNoStrong(String id){
        String regex = "^\\d{11}$";
        return id.matches(regex);
    }
    
    private boolean isPasswordStrong(String password){
        String regex = "^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*()-+=_.]).{8,15}$";
        return password.matches(regex);
    }
    
    private boolean isIdStrong(String id){
        String regex = "^(?=.*[a-zA-Z])(?=.*[0-9]).{8,23}$";
        return id.matches(regex);
    }
    
    private void checkPasswordMatch() {
        String password = J_PW.getText();
        String confirmPassword = J_PWC.getText();
        
        if(confirmPassword.isEmpty()){
            J_Test.setText(" ");
            J_Test.setForeground(new Color(255, 255, 255, 128));
        } else{
            if(password.equals(confirmPassword)){
                J_Test.setText("비밀번호가 일치합니다.");
                J_Test.setForeground(Color.BLUE);
            }
            else{
                J_Test.setText("비밀번호가 일치하지 않습니다.");
                J_Test.setForeground(Color.RED);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Login;
    private javax.swing.JButton J_Check;
    private javax.swing.JComboBox<String> J_Day;
    private javax.swing.JTextField J_ID;
    private javax.swing.JRadioButton J_Man;
    private javax.swing.JComboBox<String> J_Month;
    private javax.swing.JLabel J_NStrong;
    private javax.swing.JTextField J_Name;
    private javax.swing.JTextField J_No;
    private javax.swing.JLabel J_NoTest;
    private javax.swing.JLabel J_PStrong;
    private javax.swing.JTextField J_PW;
    private javax.swing.JTextField J_PWC;
    private javax.swing.JLabel J_Test;
    private javax.swing.JButton J_User;
    private javax.swing.JRadioButton J_Woman;
    private javax.swing.JComboBox<String> J_Year;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
