/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reserve.login;

import buisness.Business_Choice;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import reserve.data.BusinessData;
import reserve.data.ManagerData;
import reserve.data.UserData;
import reserve.file.JoinBusiness;
import reserve.file.JoinManager;
import reserve.file.JoinUser;
//import reserve.business.Business_Choice;

/**
 *
 * @author regin
 */
public class Login extends javax.swing.JFrame {
    ArrayList<BusinessData> businessInfo = new ArrayList<>();
    ArrayList<UserData> userInfo = new ArrayList<>();
    ArrayList<ManagerData> managerInfo = new ArrayList<>();
   
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        
        setTitle("로그인");
        setSize(700, 800);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F_ID = new javax.swing.JTextField();
        J_Login = new javax.swing.JButton();
        CreateID_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        F_PW = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        F_ID.setToolTipText("아이디");
        F_ID.setActionCommand("<Not Set>");
        F_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        F_ID.setName(""); // NOI18N
        F_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_IDActionPerformed(evt);
            }
        });

        J_Login.setText("로그인");
        J_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_LoginActionPerformed(evt);
            }
        });

        CreateID_Button.setText("회원가입");
        CreateID_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateID_ButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("굴림체", 1, 22)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("여행 예약 시스템");

        jLabel2.setText("아이디");

        jLabel4.setText("비밀번호");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(J_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateID_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(F_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(F_PW)))))
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(F_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(F_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(J_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CreateID_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        F_ID.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_IDActionPerformed

    private void CreateID_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateID_ButtonActionPerformed
        // TODO add your handling code here:
        SelectType click = new SelectType();
        click.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateID_ButtonActionPerformed

    private void Map(){
        J_Login.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                J_LoginActionPerformed(evt);
            }
            });
    }
    
    private void J_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_LoginActionPerformed
        // TODO add your handling code here:
        JoinBusiness businessData = new JoinBusiness();
        businessData.fRead();
        
        JoinUser userData = new JoinUser();
        userData.fRead();
        
        JoinManager managerData = new JoinManager();
        managerData.fRead();
        
        try {
            businessData.sPlite();
            businessInfo = businessData.returnBusinessInfo();
        } 
        
        catch (IOException ex) {
            ex.printStackTrace();
        }
        
        try {
            userData.sPlite();
            userInfo = userData.returnUserInfo();
        } 
        
        catch (IOException ex) {
            ex.printStackTrace();
        }
        
        try {
            managerData.sPlite();
            managerInfo = managerData.returnManagerInfo();
        } 
        
        catch (IOException ex) {
            ex.printStackTrace();
        }
        
        String ID = F_ID.getText();
        String PW = F_PW.getText();
        
        for (int j = 0; j <= userInfo.size(); j++) {
            for(int i = 0; i <= businessInfo.size(); i++){
                for(int k = 0; k <= managerInfo.size(); k++){
                    

                    if (businessInfo.get(i).getID().equals(ID) && businessInfo.get(i).getPW().equals(PW)) {
                        JOptionPane.showMessageDialog(null, "로그인 되었습니다.");
                        Business_Choice click = new Business_Choice();
                        click.setVisible(true);                
                        dispose();
                        break;
                    }

                    if(userInfo.get(j).getID().equals(ID) && userInfo.get(j).getPW().equals(PW)){
                        JOptionPane.showMessageDialog(null, "로그인 되었습니다.");
                        JFrame frame = new JFrame();
                        
                        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        frame.setSize(700, 800);
                        
                        JPanel mainPanel = new JPanel();
                        mainPanel.setLayout(new BorderLayout());
                        
                        JButton proceedButton = new JButton("예약 시스템으로 이동");
                        proceedButton.setFont(new Font("Serif", Font.PLAIN, 20));
                        proceedButton.addActionListener(new ActionListener(){
                        @Override
                            public void actionPerformed(ActionEvent e) {
                                JavaNaver.openReservationSystem(frame);
                            }
                        });
                        
                        mainPanel.add(proceedButton, BorderLayout.SOUTH);
                        frame.add(mainPanel);
                        frame.setVisible(true);
                        dispose();
                        break;
                    }
                    
                    if (managerInfo.get(i).getID().equals(ID) && managerInfo.get(i).getPW().equals(PW)) {
                        JOptionPane.showMessageDialog(null, "로그인 되었습니다.");
                        Manager click = new Manager();
                        click.setVisible(true);                
                        dispose();
                        break;
                    }

                    else{
                        JOptionPane.showMessageDialog(null, "로그인 정보가 일치하지 않습니다.");
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_J_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateID_Button;
    private javax.swing.JTextField F_ID;
    private javax.swing.JPasswordField F_PW;
    private javax.swing.JButton J_Login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
